<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="TestArrayPartition1-20180504032403" tests="1" time="0.000">
	<testcase classname="TestArrayPartition1" name="test_basic" time="0.000">
		<error message="0 != 4" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "test/test.py", line 10, in test_basic
    self.assertEqual(self.sln.ArrayPairSum([1,4,2,3]), 4)
AssertionError: 0 != 4
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
